apiVersion: v1
kind: Namespace
metadata:
  name: adl-platform
  labels:
    kubernetes.io/metadata.name: adl-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: adl-jobs
  labels:
    kubernetes.io/metadata.name: adl-jobs
