{{- /* Optional basic NetworkPolicies */ -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: adl-platform-namespace
  namespace: adl-platform
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: adl-platform
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: adl-platform
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: adl-jobs
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
    - {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: adl-jobs-namespace
  namespace: adl-jobs
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: adl-jobs
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: adl-platform
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: adl-jobs
