{{- if .Values.queryApi.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: query-api-hpa
  namespace: adl-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: query-api
  minReplicas: {{ .Values.queryApi.hpa.minReplicas }}
  maxReplicas: {{ .Values.queryApi.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.queryApi.hpa.targetCPUUtilizationPercentage }}
{{- end }}
