apiVersion: v1
kind: Service
metadata:
  name: query-api
  namespace: adl-platform
spec:
  selector:
    app: query-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.queryApi.service.port }}
      name: http
  type: ClusterIP
