{{- if .Values.scraper.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: scraper-targets
  namespace: adl-jobs
data:
  targets.txt: |-
{{- if .Values.scraper.targetUrls }}
{{- range .Values.scraper.targetUrls }}
    {{ . }}
{{- end }}
{{- end }}
{{- end }}
