{{- if .Values.scraper.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scraper-sa
  namespace: adl-jobs
  annotations:
    azure.workload.identity/client-id: {{ required "scraper workload identity clientId is required" .Values.global.azure.scraperClientId }}
{{- end }}
