{{- if .Values.scraper.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.scraper.secretProviderClass.name }}
  namespace: adl-jobs
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    workloadIdentityClientID: {{ required "scraper workload identity clientId is required" .Values.global.azure.scraperClientId }}
    keyvaultName: {{ required "keyVaultName required" .Values.global.azure.keyVaultName }}
    tenantId: {{ required "tenantId required" .Values.global.azure.tenantId }}
    objects: |
{{ .Values.scraper.secretProviderClass.objects | indent 6 }}
  secretObjects:
    - secretName: scraper-secrets
      type: Opaque
      data:
        - key: OPENAI_API_KEY
          objectName: OPENAI_API_KEY
        - key: DEEPSEEK_API_KEY
          objectName: DEEPSEEK_API_KEY
        - key: XAI_API_KEY
          objectName: XAI_API_KEY
        - key: HTTP_PROXY
          objectName: HTTP_PROXY
        - key: HTTPS_PROXY
          objectName: HTTPS_PROXY
{{- end }}
