apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: adl-kv-spc
  namespace: adl-platform
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    workloadIdentityClientID: {{ required "workload identity clientId required" .Values.global.azure.queryApiClientId }}
    keyvaultName: {{ required "keyVaultName required" .Values.global.azure.keyVaultName }}
    tenantId: {{ required "tenantId required" .Values.global.azure.tenantId }}
    objects: |
{{ .Values.secretProviderClass.objects | indent 6 }}
  secretObjects:
    - secretName: api-auth-token
      type: Opaque
      data:
        - key: API_AUTH_TOKEN
          objectName: API_AUTH_TOKEN
