apiVersion: v1
kind: ServiceAccount
metadata:
  name: query-api-sa
  namespace: adl-platform
  annotations:
    azure.workload.identity/client-id: {{ required "queryApi workload identity clientId is required" .Values.global.azure.queryApiClientId }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-qa-sa
  namespace: adl-platform
  annotations:
    azure.workload.identity/client-id: {{ required "aiQa workload identity clientId is required" .Values.global.azure.aiQaClientId }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-sa
  namespace: adl-jobs
  annotations:
    azure.workload.identity/client-id: {{ required "pipeline workload identity clientId is required" .Values.global.azure.pipelineClientId }}
